### ISSUE TITLE
[12] Add the book genres to the map draggable menu item

### ISSUE THREAD

**Issue by Chockencore** [BookswapEPFL/Bookswap#256]

**Comment by Chocolat2** [comment]
This is already implemented, see  [BookDisplayComponent.kt Lines 124-131](https://github.com/BookswapEPFL/Bookswap/blob/c628394c121aa8de8b406c7d0b7a9e47bc477489/app/src/main/java/com/android/bookswap/ui/components/BookDisplayComponent.kt#L124-L131)
