### ISSUE TITLE
[5.1] Add button to recenter the map on the user

### ISSUE THREAD

**Issue by Chockencore** [BookswapEPFL/Bookswap#59]
Add a button on the map screen to recenter the camera on the User's current position

**Comment by Chocolat2** [comment]
This is a default functionality of the GoogleMap component that can be enabled by adding the parameter `properties = MapProperties(isMyLocationEnabled = true)` to the GoogleMap(...) component call

**Comment by Chocolat2** [comment]
Not directly related to the button, but despite having the `zoomControlsEnabled = false` property set, it is still possible to zoom on the map by double tapping on the map (possibly also by pinching to zoom in/out)
